export const Types = {
  FETCH_FLIGHTS_KEY: "GET_FLIGHTS_KEY",
  FETCH_FLIGHTS_KEY_SUCCESS: "GET_FLIGHTS_KEY_SUCCESS",
  FETCH_FLIGHTS_KEY_ERROR: "GET_FLIGHTS_KEY_ERROR",

  FETCH_FLIGHTS: "GET_FLIGHTS",
  FETCH_FLIGHTS_SUCCESS: "GET_FLIGHTS_SUCCESS",
  FETCH_FLIGHTS_ERROR: "GET_FLIGHTS_ERROR",
  CLEARE_FLIGHTS: "CLEARE_FLIGHTS",

  FETCH_ALL_AIRPORTS: "GET_ALL_AIRPORTS",
  FETCH_ALL_AIRPORTS_SUCCESS: "GET_ALL_AIRPORTS_SUCCESS",
  FETCH_ALL_AIRPORTS_ERROR: "GET_ALL_AIRPORTS_ERROR",

  FLIGHT_SORT: "FLIGHT_SORT",
  SORT: "SORT",
  FILTER: "FILTER",
  DO_FILTER: "DO_FILTER",
  RESET_FILTER: "RESET_FILTER",

  FETCH_PATH: "FETCH_PATH",
  FETCH_PATH_SUCCESS: "FETCH_PATH_SUCCESS",
  FETCH_PATH_ERROR: "FETCH_PATH_ERROR",

  FETCH_RULLES: "FETCH_RULLES",
  FETCH_RULLES_SUCCESS: "FETCH_RULLES_SUCCESS",
  FETCH_RULLES_ERROR: "FETCH_RULLES_ERROR",

  FETCH_VALIDATE: "FETCH_VALIDATE",
  FETCH_VALIDATE_SUCCESS: "FETCH_VALIDATE_SUCCESS",
  FETCH_VALIDATE_ERROR: "FETCH_VALIDATE_ERROR",

  POST_VALIDATE: "POST_VALIDATE",
  POST_VALIDATE_SUCCESS: "POST_VALIDATE_SUCCESS",
  POST_VALIDATE_ERROR: "POST_VALIDATE_ERROR",

  RESET: "RESET",

  FETCH_COUNTRIES: "FETCH_COUNTRIES",
  FETCH_COUNTRIES_SUCCESS: "FETCH_COUNTRIES_SUCCESS",
  FETCH_COUNTRIES_ERROR: "FETCH_COUNTRIES_ERROR",

  POST_PRE_RESERVE: "POST_PRE_RESERVE",
  POST_PRE_RESERVE_SUCCESS: "POST_PRE_RESERVE_SUCCESS",
  POST_PRE_RESERVE_ERROR: "POST_PRE_RESERVE_ERROR",

  GET_RESERVE: "GET_RESERVE",
  GET_RESERVE_SUCCESS: "GET_RESERVE_SUCCESS",
  GET_RESERVE_ERROR: "GET_RESERVE_ERROR",

  GET_CONFIRM: "GET_CONFIRM",
  GET_CONFIRM_SUCCESS: "GET_CONFIRM_SUCCESS",
  GET_CONFIRM_ERROR: "GET_CONFIRM_ERROR",

  GET_VOCHER: "GET_VOCHER",
  GET_VOCHER_SUCCESS: "GET_VOCHER_SUCCESS",
  GET_VOCHER_ERROR: "GET_VOCHER_ERROR",
};
