export const AUTH_REGISTER = "AUTH_REGISTER";
export const AUTH_ERROR = "AUTH_ERROR";
export const AUTH_SIGN_IN = "AUTH_SIGN_IN";
export const GET_IP_LOCATION = "GET_IP_LOCATION";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_CURRENT_TOKEN = "SET_CURRENT_TOKEN";
export const EDIT_USER = "EDIT_USER";

export const HOTEL_LIST = "HOTEL_LIST";
export const HOTEL_INTERIOR_LIST = "HOTEL_INTERIOR_LIST";
export const HOTEL_FOREIGN_LIST = "HOTEL_FOREIGN_LIST";
export const HOTEL_INTERIOR_DETAILS = "HOTEL_INTERIOR_DETAILS";
export const HOTEL_FOREIGN_DETAILS = "HOTEL_FOREIGN_DETAILS";

export const SEARCH_ENTITY = "SEARCH_ENTITY";
export const PORTAL_DATA = "PORTAL_DATA";

export const HOTEL = {
  GET_INTERIOR_LIST: {
    REQUEST: "GET_INTERIOR_HOTELS_LIST_REQUEST",
    SUCCESS: "GET_INTERIOR_HOTELS_LIST_SUCCESS",
    ERROR: "GET_INTERIOR_HOTELS_LIST_ERROR",
  },
  GET_EXTERIOR_LIST: {
    REQUEST: "GET_EXTERIOR_HOTELS_LIST_REQUEST",
    SUCCESS: "GET_EXTERIOR_HOTELS_LIST_SUCCESS",
    ERROR: "GET_EXTERIOR_HOTELS_LIST_ERROR",
  },
  GET_HOTEL_DETAILS: {
    REQUEST: "GET_HOTEL_DETAILS_REQUEST",
    SUCCESS: "GET_HOTEL_DETAILS_SUCCESS",
    ERROR: "GET_HOTEL_DETAILS_ERROR",
  },
};

export const USER = {
  REGISTER: {
    REQUEST: "REGISTER_USER_REQUEST",
    SUCCESS: "REGISTER_USER_SUCCESS",
    ERROR: "REGISTER_USER_ERROR",
  },
  VERIFY_PHONE: {
    REQUEST: "VERIFY_PHONE_REQUEST",
    SUCCESS: "VERIFY_PHONE_SUCCESS",
    ERROR: "VERIFY_PHONE_ERROR",
  },
  SEND_VERIFICATION_CODE: {
    REQUEST: "SEND_VERIFICATION_CODE_REQUEST",
    SUCCESS: "SEND_VERIFICATION_CODE_SUCCESS",
    ERROR: "SEND_VERIFICATION_CODE_ERROR",
  },
  GET_IP_LOCATION: {
    REQUEST: "GET_IP_LOCATION_REQUEST",
    SUCCESS: "GET_IP_LOCATION_SUCCESS",
    ERROR: "GET_IP_LOCATION_CODE_ERROR",
  },
  FORGET_PASSWORD: {
    REQUEST: "FORGET_PASSWORD_REQUEST",
    SUCCESS: "FORGET_PASSWORD_SUCCESS",
    ERROR: "FORGET_PASSWORD_ERROR",
  },

  SET_NEW_PASSWORD: {
    REQUEST: "SET_NEW_PASSWORD_REQUEST",
    SUCCESS: "SET_NEW_PASSWORD_SUCCESS",
    ERROR: "SET_NEW_PASSWORD_ERROR",
  },
};
export const STATUS_REGISTER_MESSAGE = "STATUS_REGISTER_MESSAGE";

export const FLIGHT_LIST_SEARCH = "FLIGHT_LIST_SEARCH";
export const SET_AIRLINES = "SET_AIRLINES";
export const FLIGHT_FILTER = "FLIGHT_FILTER";
export const SET_FILTER_FLIGHT = "SET_FILTER_FLIGHT";
export const CLEAR_FILTER_FLIGHT = "CLEAR_FILTER_FLIGHT";
export const FLIGHT_SELECTED = "FLIGHT_SELECTED";
export const MIN_MAX_PRICES = "MIN_MAX_PRICES";

export const SET_USER_CREDIT_AMOUNT = "SET_USER_CREDIT_AMOUNT";
export const SET_CURRENCY = "SET_CURRENCY";
