export const Types = {
  SORT: "SORT",
  DO_FILTER: "DO_FILTER",
  FILTER: "FILTER",

  FETCH_SEARCH_TERMINAL: "FETCH_SEARCH_TERMINAL",
  FETCH_SEARCH_TERMINAL_SUCCESS: "FETCH_SEARCH_TERMINAL_SUCCESS",
  FETCH_SEARCH_TERMINAL_ERROR: "FETCH_SEARCH_TERMINAL_ERROR",

  FETCH_BUSES_KEY: "FETCH_BUSES_KEY",
  FETCH_BUSES_KEY_SUCCESS: "FETCH_BUSES_KEY_SUCCESS",
  FETCH_BUSES_KEY_ERROR: "FETCH_BUSES_KEY_ERROR",

  FETCH_BUSES: "FETCH_BUSES",
  FETCH_BUSES_SUCCESS: "FETCH_BUSES_SUCCESS",
  FETCH_BUSES_ERROR: "FETCH_BUSES_ERROR",

  FETCH_BUSES_PATH: "FETCH_BUSES_PATH",
  FETCH_BUSES_PATH_SUCCESS: "FETCH_BUSES_PATH_SUCCESS",
  FETCH_BUSES_PATH_ERROR: "FETCH_BUSES_PATH_ERROR",

  FETCH_BUSES_SEAT: "FETCH_BUSES_SEAT",
  FETCH_BUSES_SEAT_SUCCESS: "FETCH_BUSES_SEAT_SUCCESS",
  FETCH_BUSES_SEAT_ERROR: "FETCH_BUSES_SEAT_ERROR",

  FETCH_BUSES_VALIDATE: "FETCH_BUSES_VALIDATE",
  FETCH_BUSES_VALIDATE_SUCCESS: "FETCH_BUSES_VALIDATE_SUCCESS",
  FETCH_BUSES_VALIDATE_ERROR: "FETCH_BUSES_VALIDATE_ERROR",

    RESET_BUS_LIST :"RESET_BUS_LIST"

  
};
